mongodb:
  image: mongo
  entrypoint: mongod --rest --httpinterface --smallfiles

lightblue:
  image: lightblue/lightblue
  ports:
   - "8080:8080"
   - "9990:9990"
   - "9010:9010"
  entrypoint: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -Djboss.bind.address.management=0.0.0.0 -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9010 -Djava.rmi.server.hostname=0.0.0.0
 # volumes:
   #- ./drupal/:/var/www/html:rw
  links:
   - mongodb
  tty: true

